name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  type-check:
    name: Run mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install mypy
        run: pip install mypy

      - name: Run mypy
        run: mypy ndspy/

  test:
    name: Run tests [${{ matrix.os }} / Python ${{ matrix.python-version }}]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Install test dependencies
        run: pip install .[test]

      - name: Run tests
        run: pytest tests/
